name: Release to GHR
on:
  repository_dispatch:
    types: [prod-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.com

      - name: Install dependencies
        run: npm install

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update dyte-client version
        run: |
          npm install dyte-client@latest
          git add package.json package-lock.json
          git diff --quiet && git diff --staged --quiet || git commit -m "fix: dyte-client updated from remote npm registry"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
